name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ARCH: x86_64-unknown-linux-gnu
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout source code
    - uses: actions/checkout@v3
    - name: install dependencies
      run: npm install
    - name: build chrome version
      run: npx webextension-toolbox build chrome
    - name: build firefox version
      run: npx webextension-toolbox build firefox